language: node_js
node_js:
  - node
  - 7
  - 6
notifications:
  webhooks: https://hook.bearychat.com/=bwBrp/travis/93d020f67c0a20049466b93a0211692c
sudo: false
script:
  - npm run test
  - npm run build
after_success:
  - rm -fr ./dist
  - NODE_ENV=production npm run build
